Repository ottaaa/merch, pull requests merged in 2023-04, with the labels that each got.

#36 Github Actionsでモバイルアプリのテストが回るように修正
  .github/workflows/flutter_test.yaml
  mobile/gen/.gitignore
  mobile/gen/.openapi-generator-ignore
  mobile/gen/.openapi-generator/FILES
  mobile/gen/.openapi-generator/VERSION
  mobile/gen/README.md
  mobile/gen/analysis_options.yaml
  mobile/gen/doc/CreateItemDto.md
  mobile/gen/doc/ItemEntity.md
  mobile/gen/doc/ItemsApi.md
  mobile/gen/doc/ResponseItemDto.md
  mobile/gen/doc/ResponseItemDtoItem.md
  mobile/gen/doc/ResponseItemsDto.md
  mobile/gen/lib/openapi.dart
  mobile/gen/lib/src/api.dart
  mobile/gen/lib/src/api/items_api.dart
  mobile/gen/lib/src/api_util.dart
  mobile/gen/lib/src/auth/api_key_auth.dart
  mobile/gen/lib/src/auth/auth.dart
  mobile/gen/lib/src/auth/basic_auth.dart
  mobile/gen/lib/src/auth/bearer_auth.dart
  mobile/gen/lib/src/auth/oauth.dart
  mobile/gen/lib/src/date_serializer.dart
  mobile/gen/lib/src/model/create_item_dto.dart
  mobile/gen/lib/src/model/create_item_dto.g.dart
  mobile/gen/lib/src/model/date.dart
  mobile/gen/lib/src/model/item_entity.dart
  mobile/gen/lib/src/model/item_entity.g.dart
  mobile/gen/lib/src/model/response_item_dto.dart
  mobile/gen/lib/src/model/response_item_dto.g.dart
  mobile/gen/lib/src/model/response_item_dto_item.dart
  mobile/gen/lib/src/model/response_item_dto_item.g.dart
  mobile/gen/lib/src/model/response_items_dto.dart
  mobile/gen/lib/src/model/response_items_dto.g.dart
  mobile/gen/lib/src/serializers.dart
  mobile/gen/lib/src/serializers.g.dart
  mobile/gen/pubspec.yaml
  mobile/gen/test/create_item_dto_test.dart
  mobile/gen/test/item_entity_test.dart
  mobile/gen/test/items_api_test.dart
  mobile/gen/test/response_item_dto_item_test.dart
  mobile/gen/test/response_item_dto_test.dart
  mobile/gen/test/response_items_dto_test.dart
  mobile/lib/item.dart
  mobile/lib/main.dart
  mobile/lib/page/common/draw_bar.dart
  mobile/lib/page/merch.dart
  mobile/lib/page/shop.dart
  mobile/test/widget_test.dart
Labels: mobile

#42 バックエンドのテストをCIでブン回せるようにする
  .github/workflows/api_test.yaml
  api/jest.config.json
  api/package.json
Labels: CI/CD, backend

#46 バックエンドのdocker imageをalpineに変更した
  api/.dockerignore
  api/Dockerfile
  api/package-lock.json
  api/package.json
Labels: backend
